### ISSUE TITLE
API Reference is missing

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/parse-mode#10]
Perhaps we should add some JSDoc in order to have some actual content on https://doc.deno.land/https://deno.land/x/grammy_parse_mode/mod.ts?

**Comment by khaosdoctor** [comment]
I can take this

**Comment by KnorpelSenf** [comment]
@KnightNiwrem should we close this?

**Comment by KnorpelSenf** [comment]
@KnightNiwrem ping

**Comment by KnorpelSenf** [comment]
Looks done to me.
