### ISSUE TITLE
Escape strings

### ISSUE THREAD

**Issue by KnorpelSenf** [grammyjs/parse-mode#2]
Would be cool to have something like https://github.com/EdJoPaTo/telegram-format#escapetext built-in.

Should also support tagged templates (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) so that we can do 
```ts
ctx.escape`<b>Hello ${username}!</b>`
```

Requested by @KnorpelSenf (that's me) in https://t.me/grammyjs/26853

**Comment by KnightNiwrem** [comment]
Closed by https://github.com/grammyjs/parse-mode/pull/5

**Comment by KnightNiwrem** [comment]
Prefer explicit separation of structure and text, over escape.
