### ISSUE TITLE
Replying in a topic doesn't set message_thread_id

### ISSUE THREAD

**Issue by samczsun** [grammyjs/parse-mode#29]
As the title says, ``ctx.replyFmt(fmt`Foo`)`` to a message in a topic will end up going to general instead. This makes this plugin extremely clunky to use in a group with topics enabled

**Comment by KnorpelSenf** [comment]
You can just use https://github.com/grammyjs/auto-thread in combination with this plugin

**Comment by KnightNiwrem** [comment]
None of grammY's reply methods prefill message_thread_id in the first place. The replyFmt method takes in the same arguments as reply (i.e. only expands the text argument type from string to Stringable). This creates consistent behavior and expectations for the same flavor of methods.

You should use all the existing and available strategies for the Other param for reply, as you would for replyFmt.

**Comment by samczsun** [comment]
Oh, I only ever used plain reply in situations where there was no message_thread_id, so I never realized! Thanks for the super quick response!
